module.exports = [
  "Chief information officer",
  "Chief information security officer",
  "Chief technology officer",
  "IT director",
  "IT manager",
  "Cloud architect",
  "Solutions architect",
  "Computer systems manager",
  "Network architect",
  "Systems analyst",
  "IT coordinator",
  "Network administrator",
  "Network engineer",
  "System administrator",
  "Back-end developer",
  "Cloud developer",
  "Software engineer",
  "Software developer",
  "DevOps engineer",
  "Front-end developer",
  "Full-stack developer",
  "UX designer",
  "Web developer",
  "Product manager",
  "Project manager",
  "Data analyst",
];
